version: '3'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    image: marcusrenato
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge